# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LLMPaySDK_iOS_Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'LLMPay'
  # Pods for LLMPaySDK_iOS_Example

  target 'LLMPaySDK_iOS_Example-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LLMPaySDK_iOS_ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
